-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, case when(STATUS like 'DONE') then '거래완료'
when (STATUS LIKE 'RESERVED') THEN '예약중'
WHEN (STATUS LIKE 'SALE') THEN '판매중' END AS STATUS
FROM USED_GOODS_BOARD 
WHERE CREATED_DATE like '%2022-10-05%'
order by BOARD_ID desc