-- 코드를 입력하세요
SELECT B.AUTHOR_ID AS AUTHOR_ID, B.AUTHOR_NAME AS AUTHOR_NAME, A.CATEGORY AS CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE, '%Y-%m%D') LIKE '%2022-01%'
GROUP BY AUTHOR_ID, CATEGORY

ORDER BY AUTHOR_ID, CATEGORY DESC