-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) AS TOTAL_SALES
FROM AUTHOR A
LEFT OUTER JOIN BOOK B
ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT OUTER JOIN BOOK_SALES C
ON B.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC